version: '3.1'

services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - default

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    networks:
      - default
    